# Generated by Django 5.1.5 on 2025-01-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', 'update_categorias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='id_cuenta_abono',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='id_cuenta_cargo',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='monto_transaccion',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='glosa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='DetalleTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_debe', models.BooleanField()),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.cuenta')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='registros.transaccion')),
            ],
        ),
    ]
