# Generated by Django 5.1.1 on 2024-10-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEcuacionContable',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.CharField(max_length=256)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registros.categoriaecuacioncontable')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_transaccion', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_transaccion', models.DateField()),
                ('descripcion_transaccion', models.CharField(max_length=256)),
                ('id_cuenta_abono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_abono', to='registros.cuenta')),
                ('id_cuenta_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_cargo', to='registros.cuenta')),
            ],
        ),
    ]
