# Generated by Django 5.1.5 on 2025-01-26 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_rename_categoriaecuacioncontable_categoria_ecuacion_contable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='descripcion_transaccion',
        ),
        migrations.AlterField(
            model_name='categoria_ecuacion_contable',
            name='nombre_categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre_cuenta',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_cuenta_abono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haber', to='registros.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='id_cuenta_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debe', to='registros.cuenta'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='monto_transaccion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
