# Generated by Django 5.1.5 on 2025-01-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_transaccion_descripcion_transaccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
